version: "2.4"
services:
  postgres:
    image: 'postgres:latest'
    container_name: model-catalog-postgres
    environment:
      - POSTGRES_DB=${POSTGRES_DATABASE}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USERNAME}
      - PGDATA:/data/postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USERNAME} -d ${POSTGRES_DATABASE}" ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - postgres:/data/postgres
    networks:
      - model-catalog-network

  migration_execution:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./sql_scripts1:/application/model-catalog-migration-file-creator/sql_scripts/
    networks:
      - model-catalog-network

volumes:
  postgres:

networks:
  model-catalog-network: