# Code quality checks
# ---------------------------------------------
# This Github action is responsible for the code quality processes on this repository.
# 1. It performs:
# 1.1 Conventional commit checks
# 1.2 unit tests
#
# When: On every pull request and called from the CI/CD workflow on any push for develop/master/main brainch
# and any tag push to the repo.
# External Dependencies: turintech/github-actions

name: Code quality
on:
  pull_request:
    branches:
      - develop
      - master
      - main
    paths-ignore:
      - "**.md"
      - "**.yml"
      - "CODEOWNERS"

  workflow_call:

env:
  REPOSITORY_NAME: ${{ github.repository }}
  TAG_NAME: ${{ github.ref_name }}

concurrency:
  group: cq.${{ github.ref || github.run_id }}.${{ github.event_name }}
  cancel-in-progress: true

jobs:

  conventional-commit:
    name: Conventional Commits Check
    runs-on: beast
    steps:
      - name: Checkout current repository
        uses: actions/checkout@v4

      - name: Checkout remote composite actions
        uses: ./.github/workflows/composite-actions
        with:
          ACTION_APP_ID: ${{ secrets.ACTION_APP_ID }}
          ACTION_APP_KEY: ${{ secrets.ACTION_APP_KEY }}

      - name: Conventional Commit Check
        uses: ./.github/actions/code-quality/conventional-commit-check
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  unit-tests:
    name: Unit Tests
    needs: [conventional-commit]
    runs-on: beast
    steps:
      - name: Checkout current repository
        uses: actions/checkout@v4

      - name: Checkout remote composite actions
        uses: ./.github/workflows/composite-actions
        with:
          ACTION_APP_ID: ${{ secrets.ACTION_APP_ID }}
          ACTION_APP_KEY: ${{ secrets.ACTION_APP_KEY }}

      - uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: maven-${{ hashFiles('**/pom.xml') }}
          
      - uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'zulu'
          
      - name: Set up Maven
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: 3.9.5
            
      - uses: s4u/maven-settings-action@v2.8.0
        with:
          servers: |
            [{
                "id": "dataspartan-turintech-maven-releases",
                "username": "${{ secrets.CD_USER }}",
                "password": "${{ secrets.CD_PASSWORD }}"
             },
             {
                "id": "dataspartan-turintech-maven-snapshots",
                "username": "${{ secrets.CD_USER }}",
                "password": "${{ secrets.CD_PASSWORD }}"
             }
            ]
            
      - name: Code format check
        run: mvn com.coveo:fmt-maven-plugin:check
        continue-on-error: false
      
      - name: Maven test execution
        run: mvn package
        continue-on-error: false

      - name: ⬆️ Upload the coverage file as an artifact
        uses: actions/upload-artifact@v3
        with:
          name: tests-coverage
          path: ./jacoco-coverage-aggregate-report/target/site/jacoco-aggregate/jacoco.xml

